# Generated by Django 4.0.2 on 2023-01-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_usersprofile_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
