# Generated by Django 4.0.2 on 2023-01-06 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accountno', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('accountno2', models.CharField(max_length=100)),
                ('branch2', models.CharField(max_length=100)),
                ('ammount', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accountno', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('name2', models.CharField(max_length=100)),
                ('accountno2', models.CharField(max_length=100)),
                ('branch2', models.CharField(max_length=100)),
                ('ammount', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
