# Generated by Django 4.0.2 on 2023-01-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_transaction_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='money',
        ),
    ]
