# Generated by Django 4.0.2 on 2023-02-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_feedback_performance_remove_transaction_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='workdetails',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
